kurcach/first/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.first_page, name='first_page'),
]

kurcach/kurcach/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first.urls')),
    path('', include(('photorate.urls', 'photorate'), namespace='photorate')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kurcach/photorate/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('photos/', views.photo_rate, name='photo_rate'),
    path('create/', views.create, name='create'),
    path('rating/', views.RatingCreateView.as_view(), name='rating'),
]

kurcach/users/urls.py
from django.urls import path
from . import views
from users.views import logout

urlpatterns = [
    path('', views.reg, name='reg'),
    path('login/', views.log, name="log"),
    path('profile/', views.profile, name="profile"),
    path('logout/', logout, name="logout")
]

kurcach/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class MyUser(AbstractUser):
    image = models.ImageField(upload_to='media', null=True, blank=True)

kurcach/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import MyUser
from django import forms


class UserRegistrationForm(UserCreationForm):
    username_real = forms.CharField(widget=forms.TextInput(attrs={
        'id': "login", 'type': "text",'class':"fadeIn second", 'name': "login", 'placeholder': "Имя"
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'id': "login", 'type': "text",'class':"fadeIn second", 'name': "login", 'placeholder': "Логин"
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'id': "password", 'type': "text",'class': "fadeIn third", 'name': "login",'placeholder': "Пароль"
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'id': "password", 'type': "text",'class': "fadeIn third", 'name': "login",'placeholder': "Подтвердите пароль"
    }))

    class Meta:

        model = MyUser
        fields = ("username_real", "username", "password1", "password2")


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'id': "login", 'type': "text",'class':"fadeIn second", 'name': "login", 'placeholder': "Логин"
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'id': "password", 'type': "text",'class': "fadeIn third", 'name': "login", 'placeholder': "Пароль"
    }))

    class Meta:

        model = MyUser
        fields = ("username", "password")


class UserProfile(UserChangeForm):
    username_real = forms.CharField(widget=forms.TextInput)
    user_name = forms.CharField(widget=forms.TextInput)
    image = forms.ImageField(widget=forms.FileInput, required=False)

    class Meta:
        model = MyUser
        fields = ("username_real", "user_name", "image")

kurcach/users/views.py
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import render, HttpResponse, reverse
from .models import MyUser
from users.forms import UserLoginForm, UserRegistrationForm, UserProfile
from django.contrib import auth

def reg(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("login")
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, "users/register.html", context)

def log(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('photorate:photo_rate'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, "users/login.html", context)

def profile(request):
    if request.method == 'POST':
        form = UserProfile(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("profile")
        else:
            print(form.errors)
    else:
        form = UserProfile(instance=request.user)
    context = {'form': form}
    return render(request,"users/profile.html", context)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('photorate:photo_rate'))

kurcach/users/templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="stylesheet" href="{% static 'first/css/csskurcach.css' %}">
</head>
<body>
    <div class="nav">
       <a href="{% url 'first_page' %}"><h1>Фото-Оценщик</h1></a>
        <a href="{% url 'photorate:photo_rate' %}">Оценить фото</a>
        <a href="{% url 'first_page' %}">О нас</a>
        <a href="#">{{ request.user.username }}</a>
        {% if user.is_authenticated %}
                <a href="{% url 'users:logout' %}">Выйти</a>
    <a id="a2"href="{% url 'photorate:create' %}"><button type="button" name="button">Хочу оценку!</button> </a>
        {% else %}
          <a id="a1" href="{% url 'users:log' %}"><button type="button" name="button">Хочу оценку!</button></a>
    {% endif %}
    </div>
    <div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="active"> Вход </h2>


    <!-- Login Form -->


      <form method="post" action="{% url 'users:log' %}">
               {% csrf_token %}
              <p>{{ form.username }}</p>
          <p>{{ form.password }}</p>
                     <input type="submit" class="fadeIn fourth" value="Log In">
           </form>


    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a href="{% url 'users:reg' %}">Ещё нет аккаунта?</a>
    </div>

  </div>
</div>
<div class="footer2">
    <h3>Обратная связь</h3>
  <a href="#">Вконтакте</a><br>
   <a href="#">Телеграмм</a>
<p>© 2024 Все права защищены.</p>
</div>
</body>
</html>

kurcach/users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

kurcach/users/templates/users/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
      <link rel="stylesheet" href="{% static 'first/css/csskurcach.css' %}">
    <title>Title</title>
</head>
<body>
 <div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="active"> Регистрация </h2>


    <!-- Login Form -->


<form method="post" action="{% url 'users:reg' %}">
             {% csrf_token %}
      <section class="section">
        <main>
          <form id="form-Register">
              {{ form.username_real }}
              {{ form.username }}
             {{ form.password1 }}
              {{ form.password2 }}
               <input type="submit" class="fadeIn fourth" value="Создать аккаунт">
          </form>


    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a href="{% url 'users:log' %}">Уже есть аккаунт?</a>
    </div>

</body>
</html>